#include <stdio.h>

int main() {
	// BACA FILE EXTERNAL

	// FUNGSI UNTUK MENERJEMAHKAN INPUT KEDALAM LOGIKA MACHINE

	// MULAI PERMAINAN TIC TAC TOE
	// MINTA PLAYER UNTUK MEMASUKKAN AKSI BERUPA INT DARI 1 - 9
	// SETIAP AKSI TAMPILKAN CURRENT BOARD
	// GUNAKAN FUNGSI UNTUK MMENJALAN SETIAP AKSI PADA MACHINE

	// SETELAH MENCAPAI FINAL STATE, KELUARKAN PESAN ENTAH DRAW, LOSE, ATAU WIN

	return 0;
}